name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    environment: Staging
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    #- name: Copy .env
    #  working-directory: ./consulta2
    #  run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Put content in .env
      working-directory: ./consulta2
      run: |
          touch .env
          echo "${{ secrets.DOT_ENV_STAGING }}" > .env
          echo "DB_PORT=${{ job.services.mysql.ports[3306] }}" > .env
          cat .env
    
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test_db' -uroot -proot
    - name: Install Dependencies
      working-directory: ./consulta2
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute migrations
      working-directory: ./consulta2
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_CONNECTION: mysql
        DB_NAME: test_db
      run: php artisan migrate:fresh --seed --force
    - name: Generate key
      working-directory: ./consulta2
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./consulta2
      run: chmod -R 777 storage bootstrap/cache
    #- name: Create Database
    #  run: |
    #    mkdir -p database
    #    touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
